-- ═══════════════════════════════════════════════════════════════
-- 교직원 인사관리 시스템 — 현재 백엔드 실제 스키마 (ERDCloud Import용)
-- 생성: 2026-07-14 · 실 DB(MySQL 8.4) 마이그레이션 기준 · 32개 테이블
-- PK <테이블>_id 통일 + 명시적 FK → erdcloud 관계선 자동 생성
-- 사용법: erdcloud.com → 좌측 하단 Import → 아래 전체 붙여넣기
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE `allowance` (
  `allowance_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ìˆ˜ë‹¹ PK',
  `allowance_name` varchar(100) NOT NULL COMMENT 'ìˆ˜ë‹¹ëª…',
  `taxable` tinyint(1) NOT NULL COMMENT 'ê³¼ì„¸ì—¬ë¶€',
  `fixed` tinyint(1) NOT NULL COMMENT 'ê³ ì •ì—¬ë¶€',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`allowance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ìˆ˜ë‹¹ë§ˆìŠ¤í„°';
CREATE TABLE `attendance` (
  `attendance_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê·¼íƒœ PK',
  `employee_id` bigint NOT NULL,
  `work_date` date NOT NULL,
  `check_in_time` time DEFAULT NULL,
  `check_out_time` time DEFAULT NULL,
  `work_minutes` int DEFAULT NULL,
  `overtime_minutes` int DEFAULT NULL,
  `night_work_minutes` int DEFAULT NULL,
  `late_minutes` int DEFAULT NULL,
  `early_leave_minutes` int DEFAULT NULL,
  `attendance_status_code` varchar(30) NOT NULL COMMENT 'PRESENT/LATE/ABSENT/LEAVE ...',
  `remark` varchar(300) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`attendance_id`),
  UNIQUE KEY `uq_attendance_employee_date` (`employee_id`,`work_date`),
  CONSTRAINT `fk_attendance_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê·¼íƒœ';
CREATE TABLE `audit_log` (
  `audit_log_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê°ì‚¬ë¡œê·¸ PK',
  `actor_id` bigint DEFAULT NULL COMMENT 'í–‰ìœ„ìž(employee)',
  `action` varchar(50) NOT NULL COMMENT 'CREATE/UPDATE/APPROVE ...',
  `entity_type` varchar(50) DEFAULT NULL,
  `entity_id` bigint DEFAULT NULL,
  `before_data` text,
  `after_data` text,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`audit_log_id`),
  KEY `fk_audit_actor` (`actor_id`),
  CONSTRAINT `fk_audit_actor` FOREIGN KEY (`actor_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê°ì‚¬ë¡œê·¸';
CREATE TABLE `common_code` (
  `common_code_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê³µí†µì½”ë“œ PK',
  `group_code` varchar(50) NOT NULL COMMENT 'ì½”ë“œê·¸ë£¹',
  `code` varchar(50) NOT NULL COMMENT 'ì½”ë“œê°’',
  `name` varchar(100) NOT NULL COMMENT 'í‘œì‹œëª…',
  `sort_order` int NOT NULL DEFAULT '0',
  `parent_code` varchar(50) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`common_code_id`),
  UNIQUE KEY `uq_common_code` (`group_code`,`code`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê³µí†µì½”ë“œ';
CREATE TABLE `department` (
  `department_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì¡°ì§ PK',
  `department_name` varchar(100) NOT NULL COMMENT 'ì¡°ì§ëª…',
  `org_type` varchar(20) NOT NULL COMMENT 'ACADEMIC(í•™ì‚¬)/ADMINISTRATIVE(í–‰ì •)',
  `parent_department_id` bigint DEFAULT NULL COMMENT 'ìƒìœ„ì¡°ì§(ìžê¸°ì°¸ì¡°)',
  `headcount` int NOT NULL DEFAULT '0' COMMENT 'ì •ì›',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`department_id`),
  KEY `fk_department_parent` (`parent_department_id`),
  CONSTRAINT `fk_department_parent` FOREIGN KEY (`parent_department_id`) REFERENCES `department` (`department_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ë¶€ì„œ/ì¡°ì§';
CREATE TABLE `document_sequence` (
  `prefix` varchar(10) NOT NULL,
  `seq_year` int NOT NULL,
  `last_no` int NOT NULL,
  PRIMARY KEY (`prefix`,`seq_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ë¬¸ì„œë²ˆí˜¸ ì±„ë²ˆ';
CREATE TABLE `employee` (
  `employee_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'êµì§ì› PK',
  `employee_no` varchar(30) NOT NULL COMMENT 'ì‚¬ë²ˆ',
  `department_id` bigint NOT NULL COMMENT 'ì†Œì†',
  `position_id` bigint NOT NULL COMMENT 'ì§ê¸‰',
  `employment_type_id` bigint NOT NULL COMMENT 'ìž„ìš©êµ¬ë¶„',
  `name` varchar(100) NOT NULL COMMENT 'ì„±ëª…',
  `staff_category` varchar(20) NOT NULL COMMENT 'FACULTY(êµì›)/STAFF(ì§ì›)',
  `email` varchar(100) NOT NULL COMMENT 'ë¡œê·¸ì¸ ID',
  `password` varchar(255) NOT NULL COMMENT 'BCrypt',
  `role` varchar(20) NOT NULL COMMENT 'JWT ëŒ€í‘œê¶Œí•œ',
  `phone` varchar(30) DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `emergency_contact` varchar(50) DEFAULT NULL,
  `hire_date` date NOT NULL COMMENT 'ìž„ìš©ì¼',
  `resignation_date` date DEFAULT NULL,
  `employee_status_code` varchar(30) NOT NULL COMMENT 'EMPLOYED/ON_LEAVE/RESIGNED',
  `bank_name` varchar(100) DEFAULT NULL,
  `account_number` varchar(100) DEFAULT NULL,
  `account_holder` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_id`),
  UNIQUE KEY `uq_employee_no` (`employee_no`),
  UNIQUE KEY `uq_employee_email` (`email`),
  KEY `fk_employee_department` (`department_id`),
  KEY `fk_employee_position` (`position_id`),
  KEY `fk_employee_employment_type` (`employment_type_id`),
  CONSTRAINT `fk_employee_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`),
  CONSTRAINT `fk_employee_employment_type` FOREIGN KEY (`employment_type_id`) REFERENCES `employment_type` (`employment_type_id`),
  CONSTRAINT `fk_employee_position` FOREIGN KEY (`position_id`) REFERENCES `position` (`position_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='êµì§ì›(ì¸ì‚¬ê¸°ë¡ì¹´ë“œ)';
CREATE TABLE `employee_allowance` (
  `employee_allowance_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì‚¬ì›ìˆ˜ë‹¹ PK',
  `employee_id` bigint NOT NULL,
  `allowance_id` bigint NOT NULL,
  `amount` decimal(15,2) NOT NULL COMMENT 'ê¸ˆì•¡',
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_allowance_id`),
  KEY `fk_emp_allowance_employee` (`employee_id`),
  KEY `fk_emp_allowance_allowance` (`allowance_id`),
  CONSTRAINT `fk_emp_allowance_allowance` FOREIGN KEY (`allowance_id`) REFERENCES `allowance` (`allowance_id`),
  CONSTRAINT `fk_emp_allowance_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì‚¬ì›ë³„ ìˆ˜ë‹¹';
CREATE TABLE `employee_appointment` (
  `employee_appointment_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ë°œë ¹ PK',
  `document_number` varchar(30) NOT NULL COMMENT 'APT-2026-001',
  `employee_id` bigint NOT NULL COMMENT 'ë°œë ¹ëŒ€ìƒ',
  `appointment_type` varchar(50) NOT NULL COMMENT 'HIRE/PROMOTION/TRANSFER/CONCURRENT',
  `appointment_date` date NOT NULL,
  `effective_date` date DEFAULT NULL COMMENT 'ë°œíš¨ì¼',
  `from_department_id` bigint DEFAULT NULL,
  `to_department_id` bigint DEFAULT NULL,
  `from_position_id` bigint DEFAULT NULL,
  `to_position_id` bigint DEFAULT NULL,
  `reason` varchar(500) DEFAULT NULL,
  `approval_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED',
  `approver_id` bigint DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `registered_by` bigint NOT NULL COMMENT 'ë“±ë¡ìž',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_appointment_id`),
  UNIQUE KEY `uq_appointment_document_number` (`document_number`),
  KEY `fk_appointment_employee` (`employee_id`),
  KEY `fk_appointment_from_dept` (`from_department_id`),
  KEY `fk_appointment_to_dept` (`to_department_id`),
  KEY `fk_appointment_from_pos` (`from_position_id`),
  KEY `fk_appointment_to_pos` (`to_position_id`),
  KEY `fk_appointment_approver` (`approver_id`),
  KEY `fk_appointment_registrar` (`registered_by`),
  CONSTRAINT `fk_appointment_approver` FOREIGN KEY (`approver_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_appointment_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_appointment_from_dept` FOREIGN KEY (`from_department_id`) REFERENCES `department` (`department_id`),
  CONSTRAINT `fk_appointment_from_pos` FOREIGN KEY (`from_position_id`) REFERENCES `position` (`position_id`),
  CONSTRAINT `fk_appointment_registrar` FOREIGN KEY (`registered_by`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_appointment_to_dept` FOREIGN KEY (`to_department_id`) REFERENCES `department` (`department_id`),
  CONSTRAINT `fk_appointment_to_pos` FOREIGN KEY (`to_position_id`) REFERENCES `position` (`position_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì¸ì‚¬ë°œë ¹';
CREATE TABLE `employee_career` (
  `employee_career_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê²½ë ¥ PK',
  `employee_id` bigint NOT NULL,
  `company_name` varchar(200) NOT NULL COMMENT 'ê¸°ê´€/íšŒì‚¬ëª…',
  `department` varchar(100) DEFAULT NULL COMMENT 'ë¶€ì„œ',
  `position` varchar(100) DEFAULT NULL COMMENT 'ì§ìœ„',
  `job_description` varchar(500) DEFAULT NULL COMMENT 'ë‹´ë‹¹ì—…ë¬´',
  `start_date` date NOT NULL COMMENT 'ì‹œìž‘ì¼',
  `end_date` date DEFAULT NULL COMMENT 'ì¢…ë£Œì¼',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_career_id`),
  KEY `fk_career_employee` (`employee_id`),
  CONSTRAINT `fk_career_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê²½ë ¥ì‚¬í•­';
CREATE TABLE `employee_certificate` (
  `employee_certificate_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ìžê²©ì¦ PK',
  `employee_id` bigint NOT NULL,
  `name` varchar(200) NOT NULL COMMENT 'ìžê²©ì¦ëª…',
  `issuer` varchar(100) DEFAULT NULL COMMENT 'ë°œê¸‰ê¸°ê´€',
  `cert_number` varchar(100) DEFAULT NULL COMMENT 'ìžê²©ë²ˆí˜¸',
  `acquired_date` date DEFAULT NULL COMMENT 'ì·¨ë“ì¼',
  `expiry_date` date DEFAULT NULL COMMENT 'ë§Œë£Œì¼',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_certificate_id`),
  KEY `fk_certificate_employee` (`employee_id`),
  CONSTRAINT `fk_certificate_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ìžê²©ì¦ì •ë³´';
CREATE TABLE `employee_certificate_issue` (
  `employee_certificate_issue_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì¦ëª…ì„œë°œê¸‰ PK',
  `employee_id` bigint NOT NULL,
  `document_number` varchar(30) NOT NULL COMMENT 'CERT-2026-001',
  `certificate_type` varchar(100) NOT NULL COMMENT 'ìž¬ì§/ê²½ë ¥/ê¸‰ì—¬ ë“±',
  `application_date` date NOT NULL,
  `purpose` varchar(500) DEFAULT NULL,
  `issue_status` varchar(50) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING/ISSUED/REJECTED',
  `issued_at` datetime DEFAULT NULL,
  `approval_status` varchar(50) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED',
  `approver_id` bigint DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `memo` varchar(1000) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_certificate_issue_id`),
  UNIQUE KEY `uq_cert_issue_document_number` (`document_number`),
  KEY `fk_certissue_employee` (`employee_id`),
  KEY `fk_certissue_approver` (`approver_id`),
  CONSTRAINT `fk_certissue_approver` FOREIGN KEY (`approver_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_certissue_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì¦ëª…ì„œë°œê¸‰';
CREATE TABLE `employee_education` (
  `employee_education_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'í•™ë ¥ PK',
  `employee_id` bigint NOT NULL,
  `school_name` varchar(200) NOT NULL COMMENT 'í•™êµëª…',
  `major` varchar(200) DEFAULT NULL COMMENT 'ì „ê³µ',
  `degree` varchar(100) DEFAULT NULL COMMENT 'í•™ìœ„',
  `admission_date` date DEFAULT NULL COMMENT 'ìž…í•™ì¼',
  `graduation_date` date DEFAULT NULL COMMENT 'ì¡¸ì—…ì¼',
  `status` varchar(50) DEFAULT NULL COMMENT 'ì¡¸ì—…/ìž¬í•™/ìˆ˜ë£Œ/ì¤‘í‡´',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_education_id`),
  KEY `fk_education_employee` (`employee_id`),
  CONSTRAINT `fk_education_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='í•™ë ¥ì‚¬í•­';
CREATE TABLE `employee_event_support` (
  `employee_event_support_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê²½ì¡°ë¹„ PK',
  `employee_id` bigint NOT NULL,
  `document_number` varchar(30) NOT NULL COMMENT 'ES-2026-001',
  `event_type` varchar(100) NOT NULL COMMENT 'ê²°í˜¼/ì¶œì‚°/ì‚¬ë§ ë“±',
  `family_relation` varchar(100) DEFAULT NULL,
  `target_name` varchar(100) NOT NULL COMMENT 'ëŒ€ìƒìž',
  `application_date` date NOT NULL,
  `event_date` date NOT NULL,
  `requested_amount` decimal(12,0) NOT NULL COMMENT 'ì‹ ì²­ê¸ˆì•¡',
  `event_location` varchar(255) DEFAULT NULL,
  `bank_name` varchar(100) DEFAULT NULL,
  `account_number` varchar(100) DEFAULT NULL,
  `account_holder` varchar(100) DEFAULT NULL,
  `approval_status` varchar(50) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED/PAID',
  `approver_id` bigint DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `memo` varchar(1000) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_event_support_id`),
  UNIQUE KEY `uq_event_support_document_number` (`document_number`),
  KEY `fk_event_employee` (`employee_id`),
  KEY `fk_event_approver` (`approver_id`),
  CONSTRAINT `fk_event_approver` FOREIGN KEY (`approver_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_event_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê²½ì¡°ì‚¬ë¹„';
CREATE TABLE `employee_family` (
  `employee_family_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê°€ì¡± PK',
  `employee_id` bigint NOT NULL,
  `family_name` varchar(100) NOT NULL COMMENT 'ê°€ì¡±ì„±ëª…',
  `family_relation` varchar(50) NOT NULL COMMENT 'ê´€ê³„(ë¶€/ëª¨/ë°°ìš°ìž ë“±)',
  `birth_date` date DEFAULT NULL,
  `job` varchar(100) DEFAULT NULL,
  `living_together` tinyint(1) DEFAULT NULL COMMENT 'ë™ê±°ì—¬ë¶€',
  `dependent` tinyint(1) DEFAULT NULL COMMENT 'ë¶€ì–‘ì—¬ë¶€',
  `disabled` tinyint(1) DEFAULT NULL COMMENT 'ìž¥ì• ì—¬ë¶€',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_family_id`),
  KEY `fk_family_employee` (`employee_id`),
  CONSTRAINT `fk_family_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê°€ì¡±ì‚¬í•­';
CREATE TABLE `employee_language` (
  `employee_language_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì–´í•™ PK',
  `employee_id` bigint NOT NULL,
  `language_name` varchar(100) NOT NULL COMMENT 'ì–¸ì–´',
  `reading_level` varchar(50) DEFAULT NULL,
  `writing_level` varchar(50) DEFAULT NULL,
  `speaking_level` varchar(50) DEFAULT NULL,
  `test_name` varchar(100) DEFAULT NULL COMMENT 'ì‹œí—˜ëª…',
  `test_score` varchar(100) DEFAULT NULL COMMENT 'ì ìˆ˜',
  `issued_date` date DEFAULT NULL,
  `issuer` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_language_id`),
  KEY `fk_language_employee` (`employee_id`),
  CONSTRAINT `fk_language_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì–´í•™ì •ë³´';
CREATE TABLE `employee_leave_balance` (
  `employee_leave_balance_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ìž”ì—¬íœ´ê°€ PK',
  `leave_type_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `year` int NOT NULL COMMENT 'ê¸°ì¤€ì—°ë„',
  `total_days` decimal(5,1) NOT NULL COMMENT 'ë¶€ì—¬ì¼ìˆ˜',
  `used_days` decimal(5,1) NOT NULL DEFAULT '0.0' COMMENT 'ì‚¬ìš©ì¼ìˆ˜',
  `remain_days` decimal(5,1) NOT NULL COMMENT 'ìž”ì—¬ì¼ìˆ˜',
  `expire_date` date DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_leave_balance_id`),
  UNIQUE KEY `uq_balance_emp_type_year` (`employee_id`,`leave_type_id`,`year`),
  KEY `fk_balance_type` (`leave_type_id`),
  CONSTRAINT `fk_balance_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_balance_type` FOREIGN KEY (`leave_type_id`) REFERENCES `leave_type` (`leave_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ìž”ì—¬íœ´ê°€';
CREATE TABLE `employee_military` (
  `employee_military_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ë³‘ì—­ PK',
  `employee_id` bigint NOT NULL,
  `military_type` varchar(100) DEFAULT NULL COMMENT 'êµ°ë³„',
  `military_rank` varchar(100) DEFAULT NULL COMMENT 'ê³„ê¸‰',
  `discharge_type` varchar(100) DEFAULT NULL COMMENT 'ë³‘ì—­êµ¬ë¶„(ë§Œê¸°/ë©´ì œ ë“±)',
  `enlistment_date` date DEFAULT NULL,
  `discharge_date` date DEFAULT NULL,
  `exemption_reason` varchar(200) DEFAULT NULL COMMENT 'ë©´ì œì‚¬ìœ ',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employee_military_id`),
  KEY `fk_military_employee` (`employee_id`),
  CONSTRAINT `fk_military_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ë³‘ì—­ì •ë³´';
CREATE TABLE `employee_oauth` (
  `employee_oauth_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì†Œì…œê³„ì • PK',
  `employee_id` bigint NOT NULL,
  `provider` varchar(20) NOT NULL COMMENT 'KAKAO/GOOGLE/NAVER',
  `provider_user_id` varchar(100) NOT NULL COMMENT 'ì†Œì…œ ê³ ìœ  ID',
  `provider_email` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`employee_oauth_id`),
  KEY `fk_oauth_employee` (`employee_id`),
  CONSTRAINT `fk_oauth_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì†Œì…œíšŒì›ì •ë³´';
CREATE TABLE `employee_role` (
  `employee_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  PRIMARY KEY (`employee_id`,`role_id`),
  KEY `fk_er_role` (`role_id`),
  CONSTRAINT `fk_er_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_er_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì‚¬ìš©ìž-ì—­í•  ë§¤í•‘';
CREATE TABLE `employment_type` (
  `employment_type_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ìž„ìš©êµ¬ë¶„ PK',
  `employment_type_name` varchar(100) NOT NULL COMMENT 'ìž„ìš©êµ¬ë¶„ëª…',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`employment_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ìž„ìš©êµ¬ë¶„';
CREATE TABLE `file_attachment` (
  `file_attachment_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì²¨ë¶€íŒŒì¼ PK',
  `ref_type` varchar(50) NOT NULL COMMENT 'ì—…ë¬´ìœ í˜•(APPOINTMENT/EVENT ...)',
  `ref_id` bigint NOT NULL COMMENT 'ì—…ë¬´ë°ì´í„° PK',
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `extension` varchar(20) DEFAULT NULL,
  `content_type` varchar(100) DEFAULT NULL,
  `file_size` bigint NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`file_attachment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì²¨ë¶€íŒŒì¼';
CREATE TABLE `leave_policy` (
  `leave_policy_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'íœ´ê°€ì •ì±… PK',
  `position_id` bigint DEFAULT NULL COMMENT 'ì ìš© ì§ê¸‰(NULL=ì „ì²´)',
  `annual_leave_days` decimal(4,1) NOT NULL COMMENT 'ì—°ì°¨ì¼ìˆ˜',
  `max_carry_over_days` decimal(4,1) DEFAULT NULL COMMENT 'ì´ì›”í•œë„',
  `half_day_allowed` tinyint(1) DEFAULT NULL COMMENT 'ë°˜ì°¨í—ˆìš©',
  `note` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`leave_policy_id`),
  KEY `fk_leave_policy_position` (`position_id`),
  CONSTRAINT `fk_leave_policy_position` FOREIGN KEY (`position_id`) REFERENCES `position` (`position_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì§ê¸‰ë³„íœ´ê°€ì •ì±…';
CREATE TABLE `leave_request` (
  `leave_request_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'íœ´ê°€ì‹ ì²­ PK',
  `document_number` varchar(30) NOT NULL COMMENT 'LVE-2026-001',
  `leave_type_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `leave_days` decimal(4,1) NOT NULL,
  `reason` text,
  `status` varchar(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED',
  `approver_id` bigint DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`leave_request_id`),
  UNIQUE KEY `uq_leave_document_number` (`document_number`),
  KEY `fk_leave_type` (`leave_type_id`),
  KEY `fk_leave_employee` (`employee_id`),
  KEY `fk_leave_approver` (`approver_id`),
  CONSTRAINT `fk_leave_approver` FOREIGN KEY (`approver_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_leave_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_leave_type` FOREIGN KEY (`leave_type_id`) REFERENCES `leave_type` (`leave_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='íœ´ê°€ì‹ ì²­ë‚´ì—­';
CREATE TABLE `leave_type` (
  `leave_type_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'íœ´ê°€ìœ í˜• PK',
  `leave_type_name` varchar(100) NOT NULL COMMENT 'íœ´ê°€ìœ í˜•ëª…',
  `paid_yn` tinyint(1) NOT NULL COMMENT 'ìœ ê¸‰ì—¬ë¶€',
  `default_days` decimal(4,1) DEFAULT NULL COMMENT 'ê¸°ë³¸ë¶€ì—¬ì¼ìˆ˜',
  `note` varchar(255) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`leave_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='íœ´ê°€ë§ˆìŠ¤í„°';
CREATE TABLE `payroll` (
  `payroll_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê¸‰ì—¬ëª…ì„¸ì„œ PK',
  `employee_id` bigint NOT NULL,
  `payroll_year_month` varchar(6) NOT NULL COMMENT 'ê¸‰ì—¬ë…„ì›”(YYYYMM)',
  `payment_date` date DEFAULT NULL COMMENT 'ì§€ê¸‰ì¼',
  `total_pay_amount` decimal(15,2) NOT NULL COMMENT 'ì§€ê¸‰ì´ì•¡',
  `total_deduction_amount` decimal(15,2) NOT NULL COMMENT 'ê³µì œì´ì•¡',
  `real_pay_amount` decimal(15,2) NOT NULL COMMENT 'ì‹¤ì§€ê¸‰ì•¡',
  `payroll_status_code` varchar(30) DEFAULT NULL COMMENT 'DRAFT/CONFIRMED/PAID',
  `employee_name_snapshot` varchar(100) DEFAULT NULL COMMENT 'ë‹¹ì‹œ ì„±ëª… ìŠ¤ëƒ…ìƒ·',
  `department_name_snapshot` varchar(100) DEFAULT NULL COMMENT 'ë‹¹ì‹œ ì†Œì† ìŠ¤ëƒ…ìƒ·',
  `position_name_snapshot` varchar(100) DEFAULT NULL COMMENT 'ë‹¹ì‹œ ì§ê¸‰ ìŠ¤ëƒ…ìƒ·',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`payroll_id`),
  UNIQUE KEY `uq_payroll_emp_month` (`employee_id`,`payroll_year_month`),
  CONSTRAINT `fk_payroll_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê¸‰ì—¬ëª…ì„¸ì„œ';
CREATE TABLE `payroll_detail` (
  `payroll_detail_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê¸‰ì—¬ìƒì„¸ PK',
  `payroll_id` bigint NOT NULL,
  `payroll_item_master_id` bigint NOT NULL,
  `item_name_snapshot` varchar(100) NOT NULL COMMENT 'í•­ëª©ëª… ìŠ¤ëƒ…ìƒ·',
  `item_type_code` varchar(30) NOT NULL COMMENT 'PAY/DEDUCT',
  `amount` decimal(15,2) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`payroll_detail_id`),
  KEY `fk_detail_payroll` (`payroll_id`),
  KEY `fk_detail_item` (`payroll_item_master_id`),
  CONSTRAINT `fk_detail_item` FOREIGN KEY (`payroll_item_master_id`) REFERENCES `payroll_item_master` (`payroll_item_master_id`),
  CONSTRAINT `fk_detail_payroll` FOREIGN KEY (`payroll_id`) REFERENCES `payroll` (`payroll_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê¸‰ì—¬ëª…ì„¸ìƒì„¸';
CREATE TABLE `payroll_item_master` (
  `payroll_item_master_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê¸‰ì—¬í•­ëª© PK',
  `item_name` varchar(100) NOT NULL COMMENT 'í•­ëª©ëª…',
  `item_type_code` varchar(30) NOT NULL COMMENT 'PAY(ì§€ê¸‰)/DEDUCT(ê³µì œ)',
  `taxable` tinyint(1) NOT NULL COMMENT 'ê³¼ì„¸ì—¬ë¶€',
  `fixed` tinyint(1) NOT NULL COMMENT 'ê³ ì •ì—¬ë¶€',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`payroll_item_master_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê¸‰ì—¬í•­ëª©ë§ˆìŠ¤í„°';
CREATE TABLE `permission` (
  `permission_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ê¶Œí•œ PK',
  `code` varchar(80) NOT NULL COMMENT 'EMPLOYEE_READ ë“±',
  `name` varchar(80) NOT NULL,
  `resource` varchar(50) DEFAULT NULL,
  `action` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `uq_permission_code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ê¶Œí•œ';
CREATE TABLE `position` (
  `position_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì§ê¸‰ PK',
  `position_name` varchar(100) NOT NULL COMMENT 'ì§ê¸‰ëª…',
  `category` varchar(20) NOT NULL COMMENT 'FACULTY/STAFF/COMMON',
  `level` int NOT NULL DEFAULT '0' COMMENT 'ì§ê¸‰ ë ˆë²¨',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`position_id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì§ê¸‰';
CREATE TABLE `role` (
  `role_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ì—­í•  PK',
  `code` varchar(50) NOT NULL COMMENT 'ROLE_ADMIN ë“±',
  `name` varchar(50) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`role_id`),
  UNIQUE KEY `uq_role_code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì—­í• ';
CREATE TABLE `role_permission` (
  `role_id` bigint NOT NULL,
  `permission_id` bigint NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `fk_rp_permission` (`permission_id`),
  CONSTRAINT `fk_rp_permission` FOREIGN KEY (`permission_id`) REFERENCES `permission` (`permission_id`),
  CONSTRAINT `fk_rp_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ì—­í• -ê¶Œí•œ ë§¤í•‘';
